/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerValidation;
import Controller.ControllerViewEmpresa;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;

/**
 *
 * @author nel
 */
public final class ViewCaptInfProductoInsumo extends javax.swing.JPanel {

    ControllerValidation validation;
    /**
     * Creates new form ViewCaptInfProductoInsumo
     */
    public ViewCaptInfProductoInsumo() {
        validation = new ControllerValidation();
        initComponents();
        configInicial();
    }
    
    public void configInicial()
    {
        Dimension dim = super.getToolkit().getScreenSize(); 
        setBackground(new Color(44,62,80));
        setSize(dim);         
    }
    
//    private void validationInsumo(){
//        ArrayList components = new ArrayList<>();
//        components.add(nameBussines);
//        components.add(rfc);
//        components.add(street);
//        components.add(numInt);
//        components.add(numExt);
//        components.add(col);
//        components.add(codePost);
//        components.add(pagWeb);
//        components.add(eMail);
//        controller = new ControllerViewEmpresa(components);
//        controller.validations();
//    }
//    
//    private void validationProducto(){
//        ArrayList components = new ArrayList<>();
//        components.add(nameBussines);
//        components.add(rfc);
//        components.add(street);
//        components.add(numInt);
//        components.add(numExt);
//        components.add(col);
//        components.add(codePost);
//        components.add(pagWeb);
//        components.add(eMail);
//        controller = new ControllerViewEmpresa(components);
//        controller.validations();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelCliente = new javax.swing.JPanel();
        labelIdCategoria = new javax.swing.JLabel();
        labelNombreCategoria = new javax.swing.JLabel();
        labelNombreCategoria1 = new javax.swing.JLabel();
        TextIdCategoria = new javax.swing.JTextField();
        TextNombreCategoria = new javax.swing.JTextField();
        TextDescripcionCategoria = new javax.swing.JTextField();
        BotonAgregarCategoria = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelNombreCatEditDelete = new javax.swing.JLabel();
        NombreCategoriaEditDelete = new javax.swing.JTextField();
        ComboCategoria = new javax.swing.JComboBox();
        BotonEditarCategoria = new javax.swing.JButton();
        BotonEliminarCategoria = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labelIdProducto = new javax.swing.JLabel();
        labelNombreProducto = new javax.swing.JLabel();
        TextIdProducto = new javax.swing.JTextField();
        TextNombreProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTextDescripcionProducto = new javax.swing.JTextArea();
        labelDescripcionProducto = new javax.swing.JLabel();
        BotonAgregarProducto = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        labelLinkFoto = new javax.swing.JLabel();
        LabelKilos = new javax.swing.JLabel();
        LabelNumPersonas = new javax.swing.JLabel();
        LabelPrecioUnitario = new javax.swing.JLabel();
        TextLinkFoto = new javax.swing.JTextField();
        TextKilos = new javax.swing.JTextField();
        TextNumPersonas = new javax.swing.JTextField();
        TextPrecioUnitario = new javax.swing.JTextField();
        LabelBuscaCategoria = new javax.swing.JLabel();
        TextBuscaCategoria = new javax.swing.JTextField();
        ComboCategoriaProducto = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        LabelNombreProd = new javax.swing.JLabel();
        TextBuscaProducto = new javax.swing.JTextField();
        ComboProducto = new javax.swing.JComboBox();
        BotonEditarProducto = new javax.swing.JButton();
        BotonEliminarProducto = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        labelIdCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelIdCategoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelIdCategoria.setText("Id Categoria");

        labelNombreCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombreCategoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNombreCategoria.setText("Nombre");

        labelNombreCategoria1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombreCategoria1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNombreCategoria1.setText("Descripción");

        TextIdCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextIdCategoria.setForeground(new java.awt.Color(204, 204, 255));
        TextIdCategoria.setText("Id Categoria");
        TextIdCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextIdCategoriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextIdCategoriaFocusLost(evt);
            }
        });

        TextNombreCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextNombreCategoria.setForeground(new java.awt.Color(204, 204, 255));
        TextNombreCategoria.setText("Nombre de la categoria");
        TextNombreCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextNombreCategoriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextNombreCategoriaFocusLost(evt);
            }
        });

        TextDescripcionCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextDescripcionCategoria.setForeground(new java.awt.Color(204, 204, 255));
        TextDescripcionCategoria.setText("Descripcion de la categoria");
        TextDescripcionCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextDescripcionCategoriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextDescripcionCategoriaFocusLost(evt);
            }
        });

        BotonAgregarCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonAgregarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tick.png"))); // NOI18N
        BotonAgregarCategoria.setText("Agregar");

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelNombreCategoria1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelIdCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNombreCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextIdCategoria)
                    .addComponent(TextNombreCategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextDescripcionCategoria))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteLayout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(BotonAgregarCategoria)
                .addGap(153, 153, 153))
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdCategoria)
                    .addComponent(TextIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreCategoria)
                    .addComponent(TextNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreCategoria1)
                    .addComponent(TextDescripcionCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonAgregarCategoria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelNombreCatEditDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombreCatEditDelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNombreCatEditDelete.setText("Nombre de la categoria");

        NombreCategoriaEditDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NombreCategoriaEditDelete.setForeground(new java.awt.Color(204, 204, 255));
        NombreCategoriaEditDelete.setText("Buscar Categoria");
        NombreCategoriaEditDelete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombreCategoriaEditDeleteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NombreCategoriaEditDeleteFocusLost(evt);
            }
        });

        ComboCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BotonEditarCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonEditarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tick.png"))); // NOI18N
        BotonEditarCategoria.setText("Editar");

        BotonEliminarCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonEliminarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/times.png"))); // NOI18N
        BotonEliminarCategoria.setText("Eliminar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(BotonEditarCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonEliminarCategoria))
                    .addComponent(labelNombreCatEditDelete)
                    .addComponent(NombreCategoriaEditDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(ComboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombreCatEditDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NombreCategoriaEditDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEditarCategoria)
                    .addComponent(BotonEliminarCategoria))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        labelIdProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelIdProducto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelIdProducto.setText("Id Producto");

        labelNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNombreProducto.setText("Nombre");

        TextIdProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextIdProducto.setForeground(new java.awt.Color(204, 204, 255));
        TextIdProducto.setText("Id producto");
        TextIdProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextIdProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextIdProductoFocusLost(evt);
            }
        });

        TextNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextNombreProducto.setForeground(new java.awt.Color(204, 204, 255));
        TextNombreProducto.setText("Nombre del producto");
        TextNombreProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextNombreProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextNombreProductoFocusLost(evt);
            }
        });

        AreaTextDescripcionProducto.setColumns(20);
        AreaTextDescripcionProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AreaTextDescripcionProducto.setForeground(new java.awt.Color(204, 204, 204));
        AreaTextDescripcionProducto.setLineWrap(true);
        AreaTextDescripcionProducto.setRows(5);
        AreaTextDescripcionProducto.setText("Descripcion del producto");
        AreaTextDescripcionProducto.setWrapStyleWord(true);
        AreaTextDescripcionProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AreaTextDescripcionProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AreaTextDescripcionProductoFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(AreaTextDescripcionProducto);

        labelDescripcionProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDescripcionProducto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDescripcionProducto.setText("Descripcion");

        BotonAgregarProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tick.png"))); // NOI18N
        BotonAgregarProducto.setText("Agregar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelIdProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(labelDescripcionProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                    .addComponent(TextNombreProducto)
                    .addComponent(TextIdProducto))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonAgregarProducto)
                .addGap(117, 117, 117))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdProducto)
                    .addComponent(TextIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreProducto)
                    .addComponent(TextNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(labelDescripcionProducto))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonAgregarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelLinkFoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelLinkFoto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelLinkFoto.setText("Link Foto");

        LabelKilos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelKilos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelKilos.setText("Kilos");

        LabelNumPersonas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelNumPersonas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelNumPersonas.setText("No. Personas");

        LabelPrecioUnitario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelPrecioUnitario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelPrecioUnitario.setText("Precio Unitario");

        TextLinkFoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextLinkFoto.setForeground(new java.awt.Color(204, 204, 255));
        TextLinkFoto.setText("Foto");
        TextLinkFoto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextLinkFotoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextLinkFotoFocusLost(evt);
            }
        });

        TextKilos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextKilos.setForeground(new java.awt.Color(204, 204, 255));
        TextKilos.setText("Kilos");
        TextKilos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextKilosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextKilosFocusLost(evt);
            }
        });

        TextNumPersonas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextNumPersonas.setForeground(new java.awt.Color(204, 204, 255));
        TextNumPersonas.setText("Numero de personas");
        TextNumPersonas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextNumPersonasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextNumPersonasFocusLost(evt);
            }
        });

        TextPrecioUnitario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextPrecioUnitario.setForeground(new java.awt.Color(204, 204, 255));
        TextPrecioUnitario.setText("Precio unitario");
        TextPrecioUnitario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextPrecioUnitarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextPrecioUnitarioFocusLost(evt);
            }
        });

        LabelBuscaCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelBuscaCategoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelBuscaCategoria.setText("Categoria");

        TextBuscaCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextBuscaCategoria.setForeground(new java.awt.Color(204, 204, 255));
        TextBuscaCategoria.setText("Buscar Categoria");
        TextBuscaCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextBuscaCategoriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextBuscaCategoriaFocusLost(evt);
            }
        });

        ComboCategoriaProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboCategoriaProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/zoom.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(LabelPrecioUnitario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextPrecioUnitario))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelLinkFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelKilos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LabelBuscaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboCategoriaProducto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextLinkFoto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextKilos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextNumPersonas)
                            .addComponent(TextBuscaCategoria, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLinkFoto)
                    .addComponent(TextLinkFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKilos)
                    .addComponent(TextKilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNumPersonas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPrecioUnitario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextBuscaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelBuscaCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        LabelNombreProd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelNombreProd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelNombreProd.setText("Nombre del producto");

        TextBuscaProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextBuscaProducto.setForeground(new java.awt.Color(204, 204, 255));
        TextBuscaProducto.setText("Nombre del producto");
        TextBuscaProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextBuscaProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextBuscaProductoFocusLost(evt);
            }
        });

        ComboProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BotonEditarProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tick.png"))); // NOI18N
        BotonEditarProducto.setText("Editar");

        BotonEliminarProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/times.png"))); // NOI18N
        BotonEliminarProducto.setText("Eliminar");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(BotonEditarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonEliminarProducto))
                    .addComponent(TextBuscaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombreProd)
                    .addComponent(TextBuscaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEditarProducto)
                    .addComponent(BotonEliminarProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1176, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextIdCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextIdCategoriaFocusGained
        validation.placeHolder(true,TextIdCategoria,"Id Categoria");
    }//GEN-LAST:event_TextIdCategoriaFocusGained

    private void TextIdCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextIdCategoriaFocusLost
        validation.placeHolder(false ,TextIdCategoria,"Id Categoria");
    }//GEN-LAST:event_TextIdCategoriaFocusLost

    private void TextNombreCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNombreCategoriaFocusGained
        validation.placeHolder(true,TextNombreCategoria,"Nombre de la categoria");
    }//GEN-LAST:event_TextNombreCategoriaFocusGained

    private void TextNombreCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNombreCategoriaFocusLost
        validation.placeHolder(false,TextNombreCategoria,"Nombre de la categoria");
    }//GEN-LAST:event_TextNombreCategoriaFocusLost

    private void TextDescripcionCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDescripcionCategoriaFocusGained
        validation.placeHolder(true,TextDescripcionCategoria,"Descripcion de la categoria");
    }//GEN-LAST:event_TextDescripcionCategoriaFocusGained

    private void TextDescripcionCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextDescripcionCategoriaFocusLost
        validation.placeHolder(false,TextDescripcionCategoria,"Descripcion de la categoria");
    }//GEN-LAST:event_TextDescripcionCategoriaFocusLost

    private void NombreCategoriaEditDeleteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreCategoriaEditDeleteFocusGained
        validation.placeHolder(true,NombreCategoriaEditDelete,"Buscar Categoria");
    }//GEN-LAST:event_NombreCategoriaEditDeleteFocusGained

    private void NombreCategoriaEditDeleteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreCategoriaEditDeleteFocusLost
        validation.placeHolder(false,NombreCategoriaEditDelete,"Buscar Categoria");
    }//GEN-LAST:event_NombreCategoriaEditDeleteFocusLost

    private void TextIdProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextIdProductoFocusGained
        validation.placeHolder(true,TextIdProducto,"Id producto");
    }//GEN-LAST:event_TextIdProductoFocusGained

    private void TextIdProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextIdProductoFocusLost
        validation.placeHolder(false,TextIdProducto,"Id producto");
    }//GEN-LAST:event_TextIdProductoFocusLost

    private void TextNombreProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNombreProductoFocusGained
        validation.placeHolder(true,TextNombreProducto,"Nombre del producto");
    }//GEN-LAST:event_TextNombreProductoFocusGained

    private void TextNombreProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNombreProductoFocusLost
        validation.placeHolder(false,TextNombreProducto,"Nombre del producto");
    }//GEN-LAST:event_TextNombreProductoFocusLost

    private void AreaTextDescripcionProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AreaTextDescripcionProductoFocusGained
        validation.placeHolder(true,AreaTextDescripcionProducto,"Descripcion del producto");
    }//GEN-LAST:event_AreaTextDescripcionProductoFocusGained

    private void AreaTextDescripcionProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AreaTextDescripcionProductoFocusLost
        validation.placeHolder(false,AreaTextDescripcionProducto,"Descripcion del producto");
    }//GEN-LAST:event_AreaTextDescripcionProductoFocusLost

    private void TextLinkFotoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextLinkFotoFocusGained
        validation.placeHolder(true,TextLinkFoto,"Foto");
    }//GEN-LAST:event_TextLinkFotoFocusGained

    private void TextLinkFotoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextLinkFotoFocusLost
        validation.placeHolder(false,TextLinkFoto,"Foto");
    }//GEN-LAST:event_TextLinkFotoFocusLost

    private void TextKilosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextKilosFocusGained
        validation.placeHolder(true,TextKilos,"Kilos");
    }//GEN-LAST:event_TextKilosFocusGained

    private void TextKilosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextKilosFocusLost
        validation.placeHolder(false,TextKilos,"Kilos");
    }//GEN-LAST:event_TextKilosFocusLost

    private void TextNumPersonasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNumPersonasFocusGained
        validation.placeHolder(true,TextNumPersonas,"Numero de personas");
    }//GEN-LAST:event_TextNumPersonasFocusGained

    private void TextNumPersonasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNumPersonasFocusLost
        validation.placeHolder(false,TextNumPersonas,"Numero de personas");
    }//GEN-LAST:event_TextNumPersonasFocusLost

    private void TextPrecioUnitarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextPrecioUnitarioFocusGained
        validation.placeHolder(true,TextPrecioUnitario,"Precio unitario");
    }//GEN-LAST:event_TextPrecioUnitarioFocusGained

    private void TextPrecioUnitarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextPrecioUnitarioFocusLost
        validation.placeHolder(false,TextPrecioUnitario,"Precio unitario");
    }//GEN-LAST:event_TextPrecioUnitarioFocusLost

    private void TextBuscaCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextBuscaCategoriaFocusGained
        validation.placeHolder(true,TextBuscaCategoria,"Buscar Categoria");
    }//GEN-LAST:event_TextBuscaCategoriaFocusGained

    private void TextBuscaCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextBuscaCategoriaFocusLost
        validation.placeHolder(false,TextBuscaCategoria,"Buscar Categoria");
    }//GEN-LAST:event_TextBuscaCategoriaFocusLost

    private void TextBuscaProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextBuscaProductoFocusGained
        validation.placeHolder(true,TextBuscaProducto,"Nombre del producto");
    }//GEN-LAST:event_TextBuscaProductoFocusGained

    private void TextBuscaProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextBuscaProductoFocusLost
        validation.placeHolder(false,TextBuscaProducto,"Nombre del producto");
    }//GEN-LAST:event_TextBuscaProductoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTextDescripcionProducto;
    private javax.swing.JButton BotonAgregarCategoria;
    private javax.swing.JButton BotonAgregarProducto;
    private javax.swing.JButton BotonEditarCategoria;
    private javax.swing.JButton BotonEditarProducto;
    private javax.swing.JButton BotonEliminarCategoria;
    private javax.swing.JButton BotonEliminarProducto;
    private javax.swing.JComboBox ComboCategoria;
    private javax.swing.JComboBox ComboCategoriaProducto;
    private javax.swing.JComboBox ComboProducto;
    private javax.swing.JLabel LabelBuscaCategoria;
    private javax.swing.JLabel LabelKilos;
    private javax.swing.JLabel LabelNombreProd;
    private javax.swing.JLabel LabelNumPersonas;
    private javax.swing.JLabel LabelPrecioUnitario;
    private javax.swing.JTextField NombreCategoriaEditDelete;
    private javax.swing.JTextField TextBuscaCategoria;
    private javax.swing.JTextField TextBuscaProducto;
    private javax.swing.JTextField TextDescripcionCategoria;
    private javax.swing.JTextField TextIdCategoria;
    private javax.swing.JTextField TextIdProducto;
    private javax.swing.JTextField TextKilos;
    private javax.swing.JTextField TextLinkFoto;
    private javax.swing.JTextField TextNombreCategoria;
    private javax.swing.JTextField TextNombreProducto;
    private javax.swing.JTextField TextNumPersonas;
    private javax.swing.JTextField TextPrecioUnitario;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDescripcionProducto;
    private javax.swing.JLabel labelIdCategoria;
    private javax.swing.JLabel labelIdProducto;
    private javax.swing.JLabel labelLinkFoto;
    private javax.swing.JLabel labelNombreCatEditDelete;
    private javax.swing.JLabel labelNombreCategoria;
    private javax.swing.JLabel labelNombreCategoria1;
    private javax.swing.JLabel labelNombreProducto;
    private javax.swing.JPanel panelCliente;
    // End of variables declaration//GEN-END:variables
}
